apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-client
  namespace: ecommerce-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-client
  template:
    metadata:
      labels:
        app: proxy-client
    spec:
      containers:
      - name: proxy-client
        image: acrecommerce69.azurecr.io/proxy-client:0.1.0
        ports:
        - containerPort: 8900
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: ZIPKIN_BASE_URL
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config.ecommerce-system:9296"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: EUREKA_SERVER_URL
        - name: EUREKA_INSTANCE
          value: "proxy-client"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "300m"
          requests:
            memory: "512Mi"
            cpu: "150m" 