apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ecommerce-system
data:
  application.yaml: |
    spring:
      application:
        name: API-GATEWAY
      cloud:
        gateway:
          routes:
            - id: zipkin-route
              uri: http://zipkin:9411
              predicates:
                - Path=/zipkin/**
              filters:
                - StripPrefix=0
            - id: user-service-route
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/**
            - id: product-service-route
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-service/**
            - id: order-service-route
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
            - id: payment-service-route
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-service/**
            - id: shipping-service-route
              uri: lb://SHIPPING-SERVICE
              predicates:
                - Path=/shipping-service/**
            - id: favourite-service-route
              uri: lb://FAVOURITE-SERVICE
              predicates:
                - Path=/favourite-service/**
            - id: proxy-client-route
              uri: lb://PROXY-CLIENT
              predicates:
                - Path=/proxy-client/** 