apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: ecommerce-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: acrecommerce69.azurecr.io/order-service:0.1.0
        ports:
        - containerPort: 8300
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: ZIPKIN_BASE_URL
        - name: SPRING_CONFIG_IMPORT
          value: "optional:configserver:http://cloud-config.ecommerce-system:9296"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: EUREKA_SERVER_URL
        - name: EUREKA_INSTANCE
          value: "order-service"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m" 