apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: ecommerce-system
  labels:
    app: service-discovery
spec:
  selector:
    app: service-discovery
  ports:
  - port: 8761
    targetPort: 8761
    name: http
  type: NodePort  # Use NodePort for Minikube access 