apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  namespace: ecommerce-system
spec:
  selector:
    app: favourite-service
  ports:
  - port: 8800
    targetPort: 8800
  type: ClusterIP 