apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  namespace: ecommerce-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      containers:
      - name: cloud-config
        image: acrecommerce69.azurecr.io/cloud-config:0.1.0
        ports:
        - containerPort: 9296
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_ZIPKIN_BASE_URL
          value: "http://zipkin:9411"
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka"
        - name: EUREKA_INSTANCE
          value: "cloud-config"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m" 