apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  namespace: ecommerce-system
  labels:
    app: cloud-config
spec:
  selector:
    app: cloud-config
  ports:
  - port: 9296
    targetPort: 9296
    name: http
  type: NodePort  # Use NodePort for Minikube access 