apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce-system
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  ports:
  - port: 8700
    targetPort: 8700
    name: http
  type: NodePort  # Use NodePort for Minikube access 